eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8082
spring:
    application:
        name: DEFAULT-SERVICE
    data:
        mongodb:
            database: test
            host: localhost
            port: 27017

