eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8081
spring:
    application:
        name: PRODUCT-SERVICE
    data:
        mongodb:
            database: test
            host: localhost
            port: 27017
Search Tutorials
